# Generated by Django 4.0.3 on 2022-07-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_promocode_code'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promo_codes',
            field=models.ManyToManyField(to='panel.promocode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_time',
            field=models.IntegerField(default=0),
        ),
    ]
