# Generated by Django 4.0.3 on 2022-09-03 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
