# Generated by Django 4.0.3 on 2022-07-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
