# Generated by Django 4.0.3 on 2022-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_promocode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
