# Generated by Django 4.0.3 on 2022-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
